version: '3'
services:
  configuration:
    build:
      context: Configuration
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
  eureka:
    build: ./eureka
    ports: 
      - "8761:8761"
    depends_on:
      - configuration
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on:
      - configuration
  category:
    build: ./category
    ports:
      - "8081:8080"
    depends_on:
      - configuration
      - eureka
  product:
    build: ./product
    ports:
      - "8082:8082"
    depends_on:
      - configuration
      - eureka
      - category
  zuul:
    build: ./zuul
    ports:
      - "8080:8080"
    depends_on:
      - configuration
      - eureka