server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
feign:
  client:
    config:
      default:
        loggerLevel: full
spring:
  zipkin:
    base-url: http://zipkin:9411
management:
  security:
    enabled: false