server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
feign:
  client:
    config:
      default:
        loggerLevel: full
management:
  security:
    enabled: false